# Allowable options are:
# :environment        defaults to 'test'
# :min_priority       e.g. 2
# :max_priority       e.g. 10
# :number_of_workers  e.g. 2
# :pid_dir            e.g. tmp/pids Specifies an alternate directory in which to store the process ids.
# :identifier         A numeric identifier for the worker.
# :monitor            Start monitor process.
# :sleep-delay N      Amount of time to sleep in seconds when no jobs are found
# :prefix NAME        String to be prefixed to worker process names
# :command            defaults to 'bin/delayed_jobs'
guard 'delayed_jobs', environment: 'development' do
  watch(%r{^app/(.+)\.rb})
end
